# Generated by Django 3.1.7 on 2021-02-21 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='card',
            name='delimiter',
            field=models.CharField(default='default', max_length=64, verbose_name='разделитель'),
        ),
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='card',
            name='page_url',
            field=models.URLField(verbose_name='ссылка на страницу'),
        ),
        migrations.AlterField(
            model_name='card',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='field',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cards.card', verbose_name='визитка'),
        ),
        migrations.AlterField(
            model_name='field',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='порядок в списке'),
        ),
        migrations.AlterField(
            model_name='field',
            name='title',
            field=models.CharField(max_length=64, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='field',
            name='value',
            field=models.CharField(max_length=1024, verbose_name='значение'),
        ),
    ]
