# Generated by Django 3.1.7 on 2021-02-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20210221_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='page_url',
        ),
        migrations.AddField(
            model_name='card',
            name='page_path',
            field=models.CharField(default='test', max_length=128, unique=True, verbose_name='ссылка на страницу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='link',
            field=models.URLField(blank=True, verbose_name='ссылка'),
        ),
    ]
