# Generated by Django 3.1.7 on 2021-02-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20210222_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'визитка', 'verbose_name_plural': 'визитки'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['order'], 'verbose_name': 'поле', 'verbose_name_plural': 'поля'},
        ),
        migrations.AlterField(
            model_name='card',
            name='photo',
            field=models.ImageField(blank=True, upload_to='card_photos', verbose_name='фото'),
        ),
    ]
