# Generated by Django 3.1.7 on 2021-03-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210226_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='delimiter',
        ),
        migrations.AddField(
            model_name='card',
            name='displayed_name',
            field=models.CharField(default='Никнэйм', max_length=256),
        ),
    ]
