# Generated by Django 3.1.7 on 2021-03-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20210301_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='displayed_name',
            field=models.CharField(default='Никнэйм', max_length=256, verbose_name='Отображаемый ник'),
        ),
        migrations.AlterField(
            model_name='field',
            name='link',
            field=models.CharField(blank=True, max_length=256, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='field',
            name='value',
            field=models.CharField(blank=True, max_length=1024, verbose_name='значение'),
        ),
    ]
