# Generated by Django 3.1.7 on 2021-03-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20210302_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='link',
            field=models.CharField(blank=True, max_length=1024, verbose_name='ссылка'),
        ),
    ]
